
name: DeployDocs

# Controls when the action will run. Triggers the workflow on push to main branch
# events but only for the main branch
on:
  push:
    branches:
    # Push events on `main` branch
      - main
    paths: 
    - 'static/typedoc/**'
    - 'docs/src/**'
  
  # For manually triggering the build
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # ENV variables that will be used
    env:
      GH_TOKEN: ${{ secrets.GATSBY_PUBLISH_SECRET_KEY }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # extract branch name
      - name: Extract branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: extract_branch

      # Add build env for Prod
      - name: Add build Env for Prod
        if: ${{ env.BRANCH_NAME == 'release' }}
        run: echo "BUILD_ENV=PROD" >> $GITHUB_ENV

      # Add build env for Dev/Staging
      - name: Add build Env for Dev/Staging
        if: ${{ env.BRANCH_NAME == 'main' }}
        run: echo "BUILD_ENV=DEV" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use NodeJS v12.18.3
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.3'

      # Run npm install
      - name: Run npm install
        run: npm install

      # Deploy on github pages
      - name: build
        run: npm run build:gatsby
        
      # Deploy on github pages for Dev env
      - name: publish-dev
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ env.BRANCH_NAME == 'main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ./dev

      # Deploy on github pages for Prod env
      - name: publish-release
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ env.BRANCH_NAME == 'release' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ./release
